version: '2'

services:
  db:
    env_file:
      - ./.env
    restart: always
    image: postgres:9.6
    expose:
      - "5432"
  redis:
    env_file:
      - ./.env
    restart: always
    image: redis:3.0
    expose:
      - "6379"
  app:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: ./Dockerfile
    image: paindumonde-django-app:tag
    links:
      - db:db
      - redis:redis
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
